### ISSUE TITLE
Missing parentheses

### ISSUE THREAD

**Issue by eschnett** [pigworker/so-pigworker#3]
The text
```
either absurd id :: Either Void v -> v
```
on page 108 should probably have parentheses around the `v -> v` term. I think other expressions on the same page are also lacking parentheses.

**Comment by dramforever** [comment]
This one is not lacking parens.

    either :: (a -> r) -> (b -> r) -> (Either a b) -> r
    absurd :: Void -> u
    id :: p -> p
    either absurd id :: (Either Void p) -> p

Just think about it, `either foo bar` always has type `(Either p q) -> r` for some `p`, `q` and `r`. (Okay, *if* it type checks it has that type)

I didn't really check the rest.

**Comment by eschnett** [comment]
I was confused about the type of `absurd`, and probably forgot an import when testing it in ghci. Apologies for the noise.
